### ISSUE TITLE
WAD extraction is slow on Windows

### ISSUE THREAD

**Issue by vbe0201** [vbe0201/katsuba#26]
Testers needed because I don't have access to a Windows machine.

**Comment by vbe0201** [comment]
We had some test reports that did indicate an increase in performance on Windows.

Whether it is a sufficient one is still debatable and needs more insight from people who also test with `KATSUBA_WORKER_THREADS=1`.

**Comment by vbe0201** [comment]
I'm gonna go ahead and close this because I don't see ways to do better than how we are doing right now anymore.

**Comment by StarrFox** [comment]
sounds like a skill issue

**Comment by vbe0201** [comment]
You doing it for us? Thanks Starr
